name: Sensor Validation Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest
        - name: test with pytest
          run: |
            pytest validate_test.py
        
